text <- readLines("C://Users/morat/R_Analysis/week13/mikrokosmos.txt", encoding = "UTF-8")
print(text)
text <- toString(text)
print(text)
buildDictionary(ext_dic = "woorimalsam")
noun <- extractNoun(text)
print(noun)
wordcount <- table(noun)
print(wordcount)
noun <- extractNoun(text)
